# Generated by Django 3.0.4 on 2020-03-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200310_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.Category', verbose_name='category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'slug'], name='category_index'),
        ),
    ]
