# Generated by Django 3.0.4 on 2020-03-13 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20200313_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
