# Generated by Django 3.0.4 on 2020-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200313_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
